// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.mercuroo.domain;

import com.malsolo.mercuroo.domain.AddresseeDataOnDemand;
import com.malsolo.mercuroo.domain.AddresseeIntegrationTest;
import com.malsolo.mercuroo.repository.AddresseeRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AddresseeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AddresseeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AddresseeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AddresseeIntegrationTest: @Transactional;
    
    @Autowired
    AddresseeDataOnDemand AddresseeIntegrationTest.dod;
    
    @Autowired
    AddresseeRepository AddresseeIntegrationTest.addresseeRepository;
    
    @Test
    public void AddresseeIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Addressee' failed to initialize correctly", dod.getRandomAddressee());
        long count = addresseeRepository.count();
        Assert.assertTrue("Counter for 'Addressee' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AddresseeIntegrationTest.testFind() {
        Addressee obj = dod.getRandomAddressee();
        Assert.assertNotNull("Data on demand for 'Addressee' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Addressee' failed to provide an identifier", id);
        obj = addresseeRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Addressee' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Addressee' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AddresseeIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Addressee' failed to initialize correctly", dod.getRandomAddressee());
        long count = addresseeRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Addressee', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Addressee> result = addresseeRepository.findAll();
        Assert.assertNotNull("Find all method for 'Addressee' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Addressee' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AddresseeIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Addressee' failed to initialize correctly", dod.getRandomAddressee());
        long count = addresseeRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Addressee> result = addresseeRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Addressee' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Addressee' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AddresseeIntegrationTest.testFlush() {
        Addressee obj = dod.getRandomAddressee();
        Assert.assertNotNull("Data on demand for 'Addressee' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Addressee' failed to provide an identifier", id);
        obj = addresseeRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Addressee' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAddressee(obj);
        Integer currentVersion = obj.getVersion();
        addresseeRepository.flush();
        Assert.assertTrue("Version for 'Addressee' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AddresseeIntegrationTest.testSaveUpdate() {
        Addressee obj = dod.getRandomAddressee();
        Assert.assertNotNull("Data on demand for 'Addressee' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Addressee' failed to provide an identifier", id);
        obj = addresseeRepository.findOne(id);
        boolean modified =  dod.modifyAddressee(obj);
        Integer currentVersion = obj.getVersion();
        Addressee merged = addresseeRepository.save(obj);
        addresseeRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Addressee' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AddresseeIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Addressee' failed to initialize correctly", dod.getRandomAddressee());
        Addressee obj = dod.getNewTransientAddressee(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Addressee' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Addressee' identifier to be null", obj.getId());
        try {
            addresseeRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        addresseeRepository.flush();
        Assert.assertNotNull("Expected 'Addressee' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AddresseeIntegrationTest.testDelete() {
        Addressee obj = dod.getRandomAddressee();
        Assert.assertNotNull("Data on demand for 'Addressee' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Addressee' failed to provide an identifier", id);
        obj = addresseeRepository.findOne(id);
        addresseeRepository.delete(obj);
        addresseeRepository.flush();
        Assert.assertNull("Failed to remove 'Addressee' with identifier '" + id + "'", addresseeRepository.findOne(id));
    }
    
}
