// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.mercuroo.domain;

import com.malsolo.mercuroo.domain.AddresseeIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AddresseeIntegrationTest_Roo_Configurable {
    
    declare @type: AddresseeIntegrationTest: @Configurable;
    
}
