// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.mercuroo.domain;

import com.malsolo.mercuroo.domain.Addressee;
import com.malsolo.mercuroo.domain.AddresseeDataOnDemand;
import com.malsolo.mercuroo.repository.AddresseeRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AddresseeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AddresseeDataOnDemand: @Component;
    
    private Random AddresseeDataOnDemand.rnd = new SecureRandom();
    
    private List<Addressee> AddresseeDataOnDemand.data;
    
    @Autowired
    AddresseeRepository AddresseeDataOnDemand.addresseeRepository;
    
    public Addressee AddresseeDataOnDemand.getNewTransientAddressee(int index) {
        Addressee obj = new Addressee();
        setName(obj, index);
        return obj;
    }
    
    public void AddresseeDataOnDemand.setName(Addressee obj, int index) {
        String name = "name_" + index;
        if (name.length() > 100) {
            name = name.substring(0, 100);
        }
        obj.setName(name);
    }
    
    public Addressee AddresseeDataOnDemand.getSpecificAddressee(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Addressee obj = data.get(index);
        Long id = obj.getId();
        return addresseeRepository.findOne(id);
    }
    
    public Addressee AddresseeDataOnDemand.getRandomAddressee() {
        init();
        Addressee obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return addresseeRepository.findOne(id);
    }
    
    public boolean AddresseeDataOnDemand.modifyAddressee(Addressee obj) {
        return false;
    }
    
    public void AddresseeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = addresseeRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Addressee' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Addressee>();
        for (int i = 0; i < 10; i++) {
            Addressee obj = getNewTransientAddressee(i);
            try {
                addresseeRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            addresseeRepository.flush();
            data.add(obj);
        }
    }
    
}
