// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.mercuroo.domain;

import com.malsolo.mercuroo.domain.Addressee;

privileged aspect Addressee_Roo_JavaBean {
    
    public String Addressee.getName() {
        return this.name;
    }
    
    public void Addressee.setName(String name) {
        this.name = name;
    }
    
}
